# Additional Challenges

## Data Limitations

Socioeconomic data are not available within the [RIDB data](https://ridb.recreation.gov/landing) for each person making a reservation. This means that we must instead use the socioeconomic data available through [American Community Survey (ACS)](https://www.census.gov/programs-surveys/acs/data.html), which are estimates for an entire ZIP code. Therefore, we must characterize the racial breakdown of the ZIP code associated with a reservation (e.g., 60% white, 30% Hispanic Latinx, 5% Asian, and 5% black), rather than assign a reservation to a given racial group. This creates limitations when creating plots that visualize any ACS variables. 

## Technical Challenges

In the [Outdoor Equity App](https://shinyapps.bren.ucsb.edu/oe_app/), there are behavioral bugs with the plots where plots will stop updating or being created after either an input has been changed multiple times or if the input chosen is associated with a large amount of data. We were not able to troubleshoot this completely, but believe this has to do with the functions that create the visuals.

Load time for all plots especially maps is a challenge that we were able to partially tackle, but not completely. For example, we used the package `rmapshaper` [@R-rmapshaper] to simplify the geometries of the zip code and state polygons. This helped with load time significantly, but there may be other functions in `rmapshaper` [@R-rmapshaper] that may help with reducing load time in the future. This will be crucial to consider as the spatial data will grow as the data expands. For plots, we reduced load time by doing as much data wrangling as possible outside of the App so that the functions creating the plots could update more quickly. We also used the package `purr` [@R-purrr] in our functions to iterate faster than for loops. Refer to [Data Preparation Methods Section][Data Preparation Methods] to see examples of code we used for data wrangling. In the future, there is likely room to improve our functions so that they are more efficient and will therefore run faster and reduce load time in the App. 

## Future Challenges

Adding in multiple years and adding in more spatial data (beyond California) will require a larger server and likely more computing power. Refer to [How to Expand the Outdoor Equity App Section][How to Expand the Outdoor Equity App] to learn more. 

